//! `docs` — generate project documentation files (README, CHANGELOG, API, CONTRIBUTING).

use std::path::Path;

#[derive(Debug, Clone, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Kind {
    Readme,
    Changelog,
    Api,
    Contributing,
}

#[derive(Debug, Clone, serde::Deserialize)]
pub struct Args {
    pub kind: Kind,
    pub output_path: String,
    pub name: Option<String>,
    pub description: Option<String>,
    /// Force overwrite if file exists (default false).
    #[serde(default)]
    pub force: bool,
}

pub fn run(base: &Path, args: Args) -> anyhow::Result<String> {
    let content = match args.kind {
        Kind::Readme => generate_readme(&args),
        Kind::Changelog => generate_changelog(&args),
        Kind::Api => generate_api(&args),
        Kind::Contributing => generate_contributing(&args),
    };
    let out = base.join(&args.output_path);
    if out.exists() && !args.force {
        anyhow::bail!("output file already exists: {} (use force: true to overwrite)", args.output_path);
    }
    if let Some(parent) = out.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let bytes = content.len();
    std::fs::write(&out, &content)?;
    Ok(format!(
        "{{\"ok\":true,\"path\":\"{}\",\"kind\":\"{:?}\",\"bytes\":{bytes}}}",
        args.output_path, args.kind
    ))
}

fn generate_readme(args: &Args) -> String {
    let name = args.name.clone().unwrap_or_else(|| "My Project".to_string());
    let desc = args.description.clone().unwrap_or_else(|| "A project built with GOVINDA.".to_string());
    format!("# {name}\n\n{desc}\n\n## Features\n\n- _list your features here_\n\n## Installation\n\n```bash\n# clone and install\n```\n\n## Usage\n\n```bash\n# example usage\n```\n\n## Development\n\nBuilt with [GOVINDA](https://github.com/your-org/govinda-cli).\n\n## License\n\n_Your license here_\n")
}

fn generate_changelog(args: &Args) -> String {
    let name = args.name.clone().unwrap_or_else(|| "My Project".to_string());
    let now = chrono::Local::now().format("%Y-%m-%d");
    format!("# Changelog\n\nAll notable changes to **{name}** will be documented in this file.\n\nThe format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),\nand this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n\n## [Unreleased] - {now}\n\n### Added\n- Initial scaffold generated by GOVINDA\n\n### Changed\n\n### Deprecated\n\n### Removed\n\n### Fixed\n\n### Security\n")
}

fn generate_api(args: &Args) -> String {
    let name = args.name.clone().unwrap_or_else(|| "API".to_string());
    format!("# {name} API\n\n> Auto-generated stub. Expand each endpoint with method, path, parameters, and response shape.\n\n## Endpoints\n\n### `GET /health`\n\nReturns service health.\n\n**Response 200**\n```json\n{{ \"status\": \"ok\" }}\n```\n\n---\n\n_Add more endpoints here._\n")
}

fn generate_contributing(args: &Args) -> String {
    let name = args.name.clone().unwrap_or_else(|| "this project".to_string());
    format!("# Contributing to {name}\n\nThanks for your interest in contributing!\n\n## Development setup\n\n1. Fork and clone the repo\n2. Install dependencies\n3. Run the test suite\n\n## Pull requests\n\n1. Create a feature branch\n2. Make your change with tests\n3. Ensure all tests pass\n4. Open a PR with a clear description\n\n## Coding style\n\n- Follow the existing style\n- Add tests for new behavior\n- Update documentation as needed\n\n## Reporting issues\n\nUse the GitHub issue tracker. Include reproduction steps and expected vs. actual behavior.\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_readme() {
        let dir = tempfile::tempdir().unwrap();
        let args = Args {
            kind: Kind::Readme,
            output_path: "README.md".into(),
            name: Some("myproj".into()),
            description: None,
            force: true,
        };
        run(dir.path(), args).unwrap();
        let content = std::fs::read_to_string(dir.path().join("README.md")).unwrap();
        assert!(content.contains("# myproj"));
    }

    #[test]
    fn generates_changelog() {
        let dir = tempfile::tempdir().unwrap();
        let args = Args {
            kind: Kind::Changelog,
            output_path: "CHANGELOG.md".into(),
            name: None,
            description: None,
            force: true,
        };
        run(dir.path(), args).unwrap();
        let content = std::fs::read_to_string(dir.path().join("CHANGELOG.md")).unwrap();
        assert!(content.contains("# Changelog"));
    }
}
